repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-3.1.0
    hooks:
      - id: pylint
        args: [--rcfile=pyproject.toml]
        additional_dependencies: ["pylint"]
